export type ProjectDTO = Pick<
  ProjectSchema,
  | 'id'
  | 'troubleShootings'
  | 'contribution'
  | 'duration'
  | 'projectTypes'
  | 'startDate'
  | 'releaseDate'
  | 'role'
  | 'skill'
  | 'thumbnail'
  | 'title'
  | 'imageUrls'
  | 'relatedProjects'
  | 'updatedAt'
  | 'contentOverview'
  | 'contentContribution'
  | 'contentSkill'
  | 'contentReflection'
>
