/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Math = {
  _type: 'math'
  tex?: string
  display?: 'inline' | 'block'
}

export type Study = {
  _id: string
  _type: 'study'
  _createdAt: string
  _updatedAt: string
  _rev: string
  serial?: number
  title?: string
  studyCategory?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'studyCategory'
  }
  skill?: Array<string>
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
    | ({
        _key: string
      } & Math)
  >
}

export type StudyCategory = {
  _id: string
  _type: 'studyCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  studyTypes?: {
    development?: boolean
    marketing?: boolean
    design?: boolean
  }
  title?: string
  slug?: string
  skill?: Array<string>
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  summary?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  serial?: number
  projectTypes?: {
    development?: boolean
    marketing?: boolean
    design?: boolean
  }
  title?: string
  role?: string
  contribution?: string
  skill?: Array<string>
  thumbnail?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  startDate?: string
  releaseDate?: string
  summary?: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
    | ({
        _key: string
      } & Math)
  >
  contentOverview?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
  >
  contentContribution?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
  >
  contentSkill?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
  >
  contentReflection?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | ({
        _key: string
      } & Code)
  >
  troubleShootings?: Array<{
    troubleShootingType?: 0 | 1
    troubleShootingTitle?: string
    troubleShootingContent?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
      | ({
          _key: string
        } & Code)
    >
    _key: string
  }>
  images?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  relatedProjects?: Array<{
    reference?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'project'
    }
    _key: string
  }>
}

export type History = {
  _id: string
  _type: 'history'
  _createdAt: string
  _updatedAt: string
  _rev: string
  year?: 0 | 2020 | 2021 | 2022 | 2023 | 2024 | 2025
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Math
  | Study
  | StudyCategory
  | Project
  | History
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/lib/queries.ts
// Variable: HISTORY_QUERY
// Query: *[_type == "history" && !(_id in path('drafts.**')) ] | order(year){    'id': _id,    year,    content, }
export type HISTORY_QUERYResult = Array<{
  id: string
  year: 0 | 2020 | 2021 | 2022 | 2023 | 2024 | 2025 | null
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
}>
// Variable: PROJECT_LIST_QUERY
// Query: *[  _type == "project" &&   !(_id in path("drafts.**")) &&  defined(serial) &&  (    $projectType == null ||    select(      $projectType == "development" => coalesce(projectTypes.development, false) == true,      $projectType == "design"      => coalesce(projectTypes.design, false) == true,      $projectType == "marketing"   => coalesce(projectTypes.marketing, false) == true,      true    ) // 전부 false면 전체 불러오기  )] | order(coalesce(releaseDate, _updatedAt, _createdAt) desc) {  "id": _id,  "slug": string(serial),  title,  projectTypes,  startDate,  releaseDate,  "skill": skill[],  summary,  "thumbnail": coalesce(thumbnail.asset->url, "")}
export type PROJECT_LIST_QUERYResult = Array<{
  id: string
  slug: string | null
  title: string | null
  projectTypes: {
    development?: boolean
    marketing?: boolean
    design?: boolean
  } | null
  startDate: string | null
  releaseDate: string | null
  skill: Array<string> | null
  summary: string | null
  thumbnail: string | ''
}>
// Variable: PROJECT_COUNT_QUERY
// Query: count(*[  _type == "project" &&  !(_id in path("drafts.**")) &&  (    $projectType == null ||    select(      $projectType == "development" => coalesce(projectTypes.development, false) == true,      $projectType == "design"      => coalesce(projectTypes.design, false) == true,      $projectType == "marketing"   => coalesce(projectTypes.marketing, false) == true,      true    )  )])
export type PROJECT_COUNT_QUERYResult = number
// Variable: PROJECT_QUERY
// Query: *[  _type == "project" &&   defined(serial) &&  (    serial == $sNum ||           // number 비교    string(serial) == $sStr      // string 비교  )][0]{  // "키 이름" : 표현식  // 따옴표 없으면 동일한 이름  serial,  title,  summary,  projectTypes,  startDate,  releaseDate,  role,  // duration,  contribution,  "updatedAt": _updatedAt,  skill[],  "thumbnail": coalesce(thumbnail.asset->url, ""),  content[],  contentOverview[],  contentContribution[],  contentSkill[],  contentReflection[],    troubleShootings[],  "imgUrls": coalesce(images[].asset->url, ""),  // "imgUrls": images[].asset->url,  "relatedProjects": relatedProjects[]{    "reference": reference->{      title,      projectTypes,      startDate,      releaseDate,      skill[],      summary,      "thumbnail": coalesce(thumbnail.asset->url, "")    }  }}
export type PROJECT_QUERYResult = {
  serial: number | null
  title: string | null
  summary: string | null
  projectTypes: {
    development?: boolean
    marketing?: boolean
    design?: boolean
  } | null
  startDate: string | null
  releaseDate: string | null
  role: string | null
  contribution: string | null
  updatedAt: string
  skill: Array<string> | null
  thumbnail: string | ''
  content: Array<
    | ({
        _key: string
      } & Code)
    | ({
        _key: string
      } & Math)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  > | null
  contentOverview: Array<
    | ({
        _key: string
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  > | null
  contentContribution: Array<
    | ({
        _key: string
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  > | null
  contentSkill: Array<
    | ({
        _key: string
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  > | null
  contentReflection: Array<
    | ({
        _key: string
      } & Code)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  > | null
  troubleShootings: Array<{
    troubleShootingType?: 0 | 1
    troubleShootingTitle?: string
    troubleShootingContent?: Array<
      | ({
          _key: string
        } & Code)
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
    >
    _key: string
  }> | null
  imgUrls: Array<string | null> | ''
  relatedProjects: Array<{
    reference: {
      title: string | null
      projectTypes: {
        development?: boolean
        marketing?: boolean
        design?: boolean
      } | null
      startDate: string | null
      releaseDate: string | null
      skill: Array<string> | null
      summary: string | null
      thumbnail: string | ''
    } | null
  }> | null
} | null
// Variable: STUDY_LIST_QUERY
// Query: *[  _type == "study" &&   !(_id in path("drafts.**")) &&  defined(serial) ] | order(serial desc) {  "slug": string(serial),  title,  "skill": skill[],  "thumbnail": coalesce(thumbnail.asset->url, ""),  studyTypes,  "createdAt":_createdAt,  "updatedAt":_updatedAt,}
export type STUDY_LIST_QUERYResult = Array<{
  slug: string | null
  title: string | null
  skill: Array<string> | null
  thumbnail: string | ''
  studyTypes: null
  createdAt: string
  updatedAt: string
}>
// Variable: STUDY_CATEGORY_AND_RECENT_QUERY
// Query: *[    _type == "studyCategory" &&    !(_id in path("drafts.**")) &&        // ⬅️ 루트에서 draft 제외    defined(slug)                 // ⬅️ slug 없는 문서 제외(안전망)  ] | order(title asc) {    _id,    title,    slug,    skill[],    studyTypes,    summary,    "thumbnail": coalesce(thumbnail.asset->url, ""),    "recentFivePosts": *[      _type == "study" &&       !(_id in path("drafts.**")) &&      references(^._id)    ] | order(_createdAt desc)[0...3]{      _id,      title,      "slug": string(serial),      "updatedAt":_updatedAt,      "thumbnail": coalesce(thumbnail.asset->url, ""),    }  }
export type STUDY_CATEGORY_AND_RECENT_QUERYResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  skill: Array<string> | null
  studyTypes: {
    development?: boolean
    marketing?: boolean
    design?: boolean
  } | null
  summary: string | null
  thumbnail: string | ''
  recentFivePosts: Array<{
    _id: string
    title: string | null
    slug: string | null
    updatedAt: string
    thumbnail: string | ''
  }>
}>
// Variable: STUDY_CATEGORY_PAGE_QUERY
// Query: *[_type=="studyCategory" && slug==$categorySlug][0]{  _id,  title,  slug,  summary,  "thumbnail": coalesce(thumbnail.asset->url, ""),  skill[],  // 총 개수  "totalCount": count(*[    _type=="study" && !(_id in path("drafts.**")) && references(^._id)  ]),  // 페이지 슬라이스  "studyPosts": *[    _type=="study" && !(_id in path("drafts.**")) && references(^._id)  ] | order(_createdAt desc){    _id,    title,    "slug": string(serial), // 라우팅 키: /study/[serial]    "updatedAt": _updatedAt,    "thumbnail": coalesce(thumbnail.asset->url,""),  }}
export type STUDY_CATEGORY_PAGE_QUERYResult = {
  _id: string
  title: string | null
  slug: string | null
  summary: string | null
  thumbnail: string | ''
  skill: Array<string> | null
  totalCount: number
  studyPosts: Array<{
    _id: string
    title: string | null
    slug: string | null
    updatedAt: string
    thumbnail: string | ''
  }>
} | null
// Variable: STUDY_QUERY
// Query: *[  _type == "study" &&  defined(serial) &&  (    serial == $sNum ||           // number 비교    string(serial) == $sStr      // string 비교  )][0]{  // "키 이름" : 표현식  // 따옴표 없으면 동일한 이름  "slug": string(serial),  title,  "categoryTitle": studyCategory->title,  "categorySlug": studyCategory->slug,  serial,  "skill": skill[],  "thumbnail": coalesce(thumbnail.asset->url, ""),  "body": body[],  "createdAt":_createdAt,  "updatedAt":_updatedAt,}
export type STUDY_QUERYResult = {
  slug: string | null
  title: string | null
  categoryTitle: string | null
  categorySlug: string | null
  serial: number | null
  skill: Array<string> | null
  thumbnail: string | ''
  body: Array<
    | ({
        _key: string
      } & Code)
    | ({
        _key: string
      } & Math)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  > | null
  createdAt: string
  updatedAt: string
} | null
// Variable: STUDY_NEIGHBORS_QUERY
// Query: *[  _type == "study" &&  defined(serial) &&  (serial == $sNum || string(serial) == $sStr)][0]{  // 현재 문서의 기준 값  "categoryId": category._ref,  "serial": serial,  // 직전(위) 최대 2개: serial이 더 작은 것들, 내림차순으로 앞에서 2개  "prev": *[    _type == "study" &&    defined(serial) &&    serial < ^.serial &&    select(defined(^.categoryId) => category._ref == ^.categoryId, true)  ] | order(serial desc) [0...2]{    "slug": string(serial),    title,    "date": coalesce(_createdAt, _updatedAt)  },  // 직후(아래) 최대 2개: serial이 더 큰 것들, 오름차순으로 앞에서 2개  "next": *[    _type == "study" &&    defined(serial) &&    serial > ^.serial &&    select(defined(^.categoryId) => category._ref == ^.categoryId, true)  ] | order(serial asc) [0...2]{    "slug": string(serial),    title,    "date": coalesce(_createdAt, _updatedAt)  }}
export type STUDY_NEIGHBORS_QUERYResult = {
  categoryId: null
  serial: number | null
  prev: Array<{
    slug: string | null
    title: string | null
    date: string
  }>
  next: Array<{
    slug: string | null
    title: string | null
    date: string
  }>
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    "*[_type == \"history\" && !(_id in path('drafts.**')) ] | order(year){\n    'id': _id,\n    year,\n    content,\n }": HISTORY_QUERYResult
    '\n*[\n  _type == "project" && \n  !(_id in path("drafts.**")) &&\n  defined(serial) &&\n  (\n    $projectType == null ||\n    select(\n      $projectType == "development" => coalesce(projectTypes.development, false) == true,\n      $projectType == "design"      => coalesce(projectTypes.design, false) == true,\n      $projectType == "marketing"   => coalesce(projectTypes.marketing, false) == true,\n      true\n    ) // \uC804\uBD80 false\uBA74 \uC804\uCCB4 \uBD88\uB7EC\uC624\uAE30\n  )\n] | order(coalesce(releaseDate, _updatedAt, _createdAt) desc) {\n  "id": _id,\n  "slug": string(serial),\n  title,\n  projectTypes,\n  startDate,\n  releaseDate,\n  "skill": skill[],\n  summary,\n  "thumbnail": coalesce(thumbnail.asset->url, "")\n}\n': PROJECT_LIST_QUERYResult
    '\ncount(*[\n  _type == "project" &&\n  !(_id in path("drafts.**")) &&\n  (\n    $projectType == null ||\n    select(\n      $projectType == "development" => coalesce(projectTypes.development, false) == true,\n      $projectType == "design"      => coalesce(projectTypes.design, false) == true,\n      $projectType == "marketing"   => coalesce(projectTypes.marketing, false) == true,\n      true\n    )\n  )\n])\n': PROJECT_COUNT_QUERYResult
    '\n*[\n  _type == "project" && \n  defined(serial) &&\n  (\n    serial == $sNum ||           // number \uBE44\uAD50\n    string(serial) == $sStr      // string \uBE44\uAD50\n  )\n][0]{\n  // "\uD0A4 \uC774\uB984" : \uD45C\uD604\uC2DD\n  // \uB530\uC634\uD45C \uC5C6\uC73C\uBA74 \uB3D9\uC77C\uD55C \uC774\uB984\n  serial,\n  title,\n  summary,\n  projectTypes,\n  startDate,\n  releaseDate,\n  role,\n  // duration,\n  contribution,\n  "updatedAt": _updatedAt,\n\n  skill[],\n\n  "thumbnail": coalesce(thumbnail.asset->url, ""),\n  content[],\n  contentOverview[],\n  contentContribution[],\n  contentSkill[],\n  contentReflection[],\n  \n  troubleShootings[],\n  "imgUrls": coalesce(images[].asset->url, ""),\n  // "imgUrls": images[].asset->url,\n  "relatedProjects": relatedProjects[]{\n    "reference": reference->{\n      title,\n      projectTypes,\n      startDate,\n      releaseDate,\n      skill[],\n      summary,\n      "thumbnail": coalesce(thumbnail.asset->url, "")\n    }\n  }\n}\n': PROJECT_QUERYResult
    '\n*[\n  _type == "study" && \n  !(_id in path("drafts.**")) &&\n  defined(serial) \n] | order(serial desc) {\n  "slug": string(serial),\n  title,\n  "skill": skill[],\n  "thumbnail": coalesce(thumbnail.asset->url, ""),\n  studyTypes,\n  "createdAt":_createdAt,\n  "updatedAt":_updatedAt,\n}\n': STUDY_LIST_QUERYResult
    '\n  *[\n    _type == "studyCategory" &&\n    !(_id in path("drafts.**")) &&        // \u2B05\uFE0F \uB8E8\uD2B8\uC5D0\uC11C draft \uC81C\uC678\n    defined(slug)                 // \u2B05\uFE0F slug \uC5C6\uB294 \uBB38\uC11C \uC81C\uC678(\uC548\uC804\uB9DD)\n  ] | order(title asc) {\n    _id,\n    title,\n    slug,\n    skill[],\n    studyTypes,\n    summary,\n    "thumbnail": coalesce(thumbnail.asset->url, ""),\n    "recentFivePosts": *[\n      _type == "study" && \n      !(_id in path("drafts.**")) &&\n      references(^._id)\n    ] | order(_createdAt desc)[0...3]{\n      _id,\n      title,\n      "slug": string(serial),\n      "updatedAt":_updatedAt,\n      "thumbnail": coalesce(thumbnail.asset->url, ""),\n    }\n  }\n': STUDY_CATEGORY_AND_RECENT_QUERYResult
    '\n*[_type=="studyCategory" && slug==$categorySlug][0]{\n  _id,\n  title,\n  slug,\n  summary,\n  "thumbnail": coalesce(thumbnail.asset->url, ""),\n  skill[],\n  // \uCD1D \uAC1C\uC218\n  "totalCount": count(*[\n    _type=="study" && !(_id in path("drafts.**")) && references(^._id)\n  ]),\n  // \uD398\uC774\uC9C0 \uC2AC\uB77C\uC774\uC2A4\n  "studyPosts": *[\n    _type=="study" && !(_id in path("drafts.**")) && references(^._id)\n  ] | order(_createdAt desc){\n    _id,\n    title,\n    "slug": string(serial), // \uB77C\uC6B0\uD305 \uD0A4: /study/[serial]\n    "updatedAt": _updatedAt,\n    "thumbnail": coalesce(thumbnail.asset->url,""),\n  }\n}\n': STUDY_CATEGORY_PAGE_QUERYResult
    '\n*[\n  _type == "study" &&\n  defined(serial) &&\n  (\n    serial == $sNum ||           // number \uBE44\uAD50\n    string(serial) == $sStr      // string \uBE44\uAD50\n  )\n][0]{\n  // "\uD0A4 \uC774\uB984" : \uD45C\uD604\uC2DD\n  // \uB530\uC634\uD45C \uC5C6\uC73C\uBA74 \uB3D9\uC77C\uD55C \uC774\uB984\n  "slug": string(serial),\n  title,\n  "categoryTitle": studyCategory->title,\n  "categorySlug": studyCategory->slug,\n  serial,\n  "skill": skill[],\n  "thumbnail": coalesce(thumbnail.asset->url, ""),\n  "body": body[],\n  "createdAt":_createdAt,\n  "updatedAt":_updatedAt,\n}\n': STUDY_QUERYResult
    '\n*[\n  _type == "study" &&\n  defined(serial) &&\n  (serial == $sNum || string(serial) == $sStr)\n][0]{\n  // \uD604\uC7AC \uBB38\uC11C\uC758 \uAE30\uC900 \uAC12\n  "categoryId": category._ref,\n  "serial": serial,\n\n  // \uC9C1\uC804(\uC704) \uCD5C\uB300 2\uAC1C: serial\uC774 \uB354 \uC791\uC740 \uAC83\uB4E4, \uB0B4\uB9BC\uCC28\uC21C\uC73C\uB85C \uC55E\uC5D0\uC11C 2\uAC1C\n  "prev": *[\n    _type == "study" &&\n    defined(serial) &&\n    serial < ^.serial &&\n    select(defined(^.categoryId) => category._ref == ^.categoryId, true)\n  ] | order(serial desc) [0...2]{\n    "slug": string(serial),\n    title,\n    "date": coalesce(_createdAt, _updatedAt)\n  },\n\n  // \uC9C1\uD6C4(\uC544\uB798) \uCD5C\uB300 2\uAC1C: serial\uC774 \uB354 \uD070 \uAC83\uB4E4, \uC624\uB984\uCC28\uC21C\uC73C\uB85C \uC55E\uC5D0\uC11C 2\uAC1C\n  "next": *[\n    _type == "study" &&\n    defined(serial) &&\n    serial > ^.serial &&\n    select(defined(^.categoryId) => category._ref == ^.categoryId, true)\n  ] | order(serial asc) [0...2]{\n    "slug": string(serial),\n    title,\n    "date": coalesce(_createdAt, _updatedAt)\n  }\n}\n': STUDY_NEIGHBORS_QUERYResult
  }
}
